Repository petpple/member, pull requests merged in 2023-02, with the labels that each got.

#111 ⚡️ :: (#106) memberFsitterList 수정 - 소연
  src/main/java/petpple/kiwi/member/controller/Member/MemberFosterServiceController.java
  src/main/java/petpple/kiwi/member/domain/fosterService/FosterService.java
  src/main/java/petpple/kiwi/member/repository/fService/IFosterService.java
  src/main/resources/mybatis-mapper/FosterSerivceMapper.xml
  src/main/resources/static/images/member/member/N4YGIWJSWY.jpg
  src/main/resources/static/images/member/pet/N2Y5NPR7.jpg
  src/main/resources/static/images/member/pet/W7HCLXM8.jpg
  src/main/webapp/WEB-INF/views/member/fsitterAjaxList.jsp
  src/main/webapp/WEB-INF/views/member/fsitterPetSitterList.jsp
Labels: chore, 기능 추가

#115 ⚡️ :: (#112) member FsitterList 수정 - 소연
  src/main/java/petpple/kiwi/member/controller/Member/MemberFosterServiceController.java
  src/main/java/petpple/kiwi/member/domain/apply/ReviewProfile.java
  src/main/java/petpple/kiwi/member/domain/apply/Sitter.java
  src/main/java/petpple/kiwi/member/domain/fosterService/FosterService.java
  src/main/resources/mybatis-mapper/FosterSerivceMapper.xml
  src/main/webapp/WEB-INF/views/member/fsitterAjaxList.jsp
  src/main/webapp/WEB-INF/views/member/fsitterMyProfile.jsp
  src/main/webapp/WEB-INF/views/member/fsitterPetSitterList.jsp
Labels: chore, 기능 추가

#117 📑 :: (#110) 멤버 후기 작성 기능 구현 - 현성
  src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
  src/main/java/petpple/kiwi/member/controller/Member/MemberReviewController.java
  src/main/java/petpple/kiwi/member/domain/review/Review.java
  src/main/java/petpple/kiwi/member/repository/review/IReview.java
  src/main/resources/mybatis-mapper/Review.xml
  src/main/resources/static/images/member/review/V1249Q6L1DHDNI0.jpg
  src/main/resources/static/images/member/review/V1249Q6L1DHDNI1.jpg
  src/main/resources/static/images/member/review/V1249Q6L1DHDNI2.jpg
  src/main/webapp/WEB-INF/views/member/memberReviewForm.jsp
Labels: 기능 추가

#119 📑 :: (#107) 긴급 서비스 관련 페이지 수정 및 매핑(미완) - 보영
  src/main/java/petpple/kiwi/member/controller/Member/MemberController.java
  src/main/java/petpple/kiwi/member/controller/Member/MemberUrgentServiceController.java
  src/main/webapp/WEB-INF/views/member/header.jsp
  src/main/webapp/WEB-INF/views/member/memberCareTypeCho.jsp
  src/main/webapp/WEB-INF/views/member/memberSvcTypeCho.jsp
  src/main/webapp/WEB-INF/views/member/memberUsvcDetail.jsp
  src/main/webapp/WEB-INF/views/member/memberUsvcForm.jsp
  src/main/webapp/WEB-INF/views/member/memberUsvcPetCho.jsp
Labels: chore, 기능 추가

#123 ⚡️ :: (#121) memberSide url 변경 - 보영
  src/main/webapp/WEB-INF/views/member/memberCareTypeCho.jsp
  src/main/webapp/WEB-INF/views/member/memberSvcTypeCho.jsp
  src/main/webapp/WEB-INF/views/member/memberUsvcForm.jsp
  src/main/webapp/WEB-INF/views/member/memberUsvcPetCho.jsp
Labels: chore
